version: 2.1
jobs:
    build_and_deploy:
      docker:
          - image: circleci/node:14
      environment:
        TARGET_PROJECT: test-circle-ci-99504
      steps:
          - checkout
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "functions/package.json" }}
                    - v1-dependencies-
          - run:
                name: Install Dependencies
                command: cd functions && npm install
          - save_cache:
                key: v1-npm-deps-{{ checksum "functions/package-lock.json" }}
                paths:
                    - ./functions/node_modules
          - run:
                name: Choose Project
                command: cd functions && ./node_modules/.bin/firebase use $TARGET_PROJECT
          - run:
                name: Firebase Deploy
                command: cd functions && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only functions

    trigger_automation_test:
      docker:
          - image: circleci/node:14
      steps:
          - run:
              name: Kick off auotmation test frontend
              command: |
                curl --location --request POST 'https://circleci.com/api/v2/project/github/TuyenHoangPG/cicd-frontend/pipeline?branch=build' \
                --header 'Content-Type: application/json' \
                -u "1ea9cc1a016c3f6d452b22699929fd107dccd6a7" \
                --data-raw '{"branch":"build"}'
workflows:
  my-pipeline:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - build
      - trigger_automation_test:
          requires:
            - build_and_deploy
          filters:
            branches:
              only:
                - build


